#!/bin/bash
# Build memtier and on Heroku.

MEMTIER_VERSION=${MEMTIER_VERSION-1.3.0}

memtier_tarball_url=https://github.com/RedisLabs/memtier_benchmark/archive/${MEMTIER_VERSION}.tar.gz

temp_dir=$(mktemp -d /tmp/memtier.XXXXXXXXXX)

cd $temp_dir
echo "Temp dir: $temp_dir"

echo "Downloading $memtier_tarball_url"
curl -L $memtier_tarball_url | tar xzv

(
  cd memtier_benchmark-${MEMTIER_VERSION}
  autoreconf -ivf
  ./configure --prefix=/tmp/memtier
  make
  make install
)

cp /tmp/memtier/bin/memtier_benchmark $1
